### PR TITLE
Don't error if preview update is interrupted by window closure

### LINKED ISSUE #196: Javascript exception when new project is created.
Inky

Inky version: 0.10.0
ink version: 0.8.2
inkjs version: 1.7.1 with hotfix
windows 64
1. Open the app. 
2. Open left menu bar.
3. File - new project
4. Close new created window.

"object has been destroyed"

### PR DESCRIPTION
**Pull request by lunarcloud**
Fix #196  which isn't Linux-exclusive like I thought it was, reading the issue now.

### CODE REVIEW

**Comment by joethephish** [comment]
Hmm, I'm not able to reproduce this [on mac], so I'd like a little bit more scrutiny before merging:

* Where does "Object has been destroyed" appear? As a popup dialog?
* Do we know what object exactly it's referring to? Is there maybe some kind of race condition between processes while we're shutting down?
* Is there maybe a way we could check for the object's existence rather than doing a try...catch and string matching the error message?
* This commit introduces tab indentation into a space-indented file (sorry!)

**Comment by lunarcloud** [comment]
To reproduce,
1. Open a pre-existing ink file
2. save a change
3. close the window
4. observe the popup
image

**Comment by lunarcloud** [comment]
I beleive it's referring to the requester, but checking for '.isDestroyed()' before making the call doesn't work and checking it in the exception catch reveals it becomes true during the send.

I tried doing `if (!requester.isDestroyed && session.evaluatingExpression)` but it didn't fix the issue

**Comment by lunarcloud** [comment]
If I put this inside the catch:
```
    requester.send...
  }
} catch (e) {
  console.error('Error', e.message, session, requester);
  ...
```

It creates this log:
```
Error Object has been destroyed { process:
   ChildProcess {
     _events:
      { close: [Function: processCloseExit],
        exit: [Function: processCloseExit] },
     _eventsCount: 2,
     _maxListeners: undefined,
     _closesNeeded: 3,
     _closesGot: 1,
     connected: false,
     signalCode: 'SIGTERM',
     exitCode: null,
     killed: true,
     spawnfile:
      '/home/sam/GitHub/forks/inky/app/main-process/ink/inklecate_linux',
     _handle: null,
     spawnargs:
      [ '/home/sam/GitHub/forks/inky/app/main-process/ink/inklecate_linux',
        '-ckp',
        '/tmp/inky_compile/test_ink_Nc5XJ0l/test.ink' ],
     pid: 25330,
     stdin:
      Socket {
        connecting: false,
        _hadError: false,
        _handle: null,
        _parent: null,
        _host: null,
        _readableState: [ReadableState],
        readable: false,
        _events: [Object],
        _eventsCount: 1,
        _maxListeners: undefined,
        _writableState: [WritableState],
        writable: false,
        allowHalfOpen: false,
        _sockname: null,
        _pendingData: null,
        _pendingEncoding: '',
        server: null,
        _server: null,
        [Symbol(asyncId)]: 58,
        [Symbol(lastWriteQueueSize)]: 0,
        [Symbol(timeout)]: null,
        [Symbol(kBytesRead)]: 0,
        [Symbol(kBytesWritten)]: 0 },
     stdout:
      Socket {
        connecting: false,
        _hadError: false,
        _handle: [Pipe],
        _parent: null,
        _host: null,
        _readableState: [ReadableState],
        readable: true,
        _events: [Object],
        _eventsCount: 3,
        _maxListeners: undefined,
        _writableState: [WritableState],
        writable: false,
        allowHalfOpen: false,
        _sockname: null,
        _pendingData: null,
        _pendingEncoding: '',
        server: null,
        _server: null,
        [Symbol(asyncId)]: 59,
        [Symbol(lastWriteQueueSize)]: 0,
        [Symbol(timeout)]: null,
        [Symbol(kBytesRead)]: 0,
        [Symbol(kBytesWritten)]: 0 },
     stderr:
      Socket {
        connecting: false,
        _hadError: false,
        _handle: [Pipe],
        _parent: null,
        _host: null,
        _readableState: [ReadableState],
        readable: true,
        _events: [Object],
        _eventsCount: 3,
        _maxListeners: undefined,
        _writableState: [WritableState],
        writable: false,
        allowHalfOpen: false,
        _sockname: null,
        _pendingData: null,
        _pendingEncoding: '',
        server: null,
        _server: null,
        [Symbol(asyncId)]: 60,
        [Symbol(lastWriteQueueSize)]: 0,
        [Symbol(timeout)]: null,
        [Symbol(kBytesRead)]: 0,
        [Symbol(kBytesWritten)]: 0 },
     stdio: [ [Socket], [Socket], [Socket] ] },
  requesterWebContents:
   WebContents {
     webContents: [Circular],
     history:
      [ 'file:///home/sam/GitHub/forks/inky/app/renderer/index.html' ],
     currentIndex: 0,
     pendingIndex: -1,
     inPageIndex: -1,
     _events:
      { 'navigation-entry-commited': [Function],
        'ipc-message': [Function],
        'ipc-message-sync': [Function],
        'ipc-internal-message': [Function],
        'ipc-internal-message-sync': [Function],
        'pepper-context-menu': [Function],
        'remote-require': [Function],
        'remote-get-global': [Function],
        'remote-get-builtin': [Function],
        'remote-get-current-window': [Function],
        'remote-get-current-web-contents': [Function],
        'remote-get-guest-web-contents': [Function],
        '-did-get-response-details': [Function],
        '-did-get-redirect-request': [Function],
        'devtools-reload-page': [Function],
        '-new-window': [Function],
        '-web-contents-created': [Function],
        '-add-new-contents': [Function],
        'will-navigate': [Function],
        'did-navigate': [Function],
        'devtools-opened': [Function],
        move: [Function],
        activate: [Function],
        'page-title-updated': [Function],
        'dom-ready': [Array] },
     _eventsCount: 25,
     _maxListeners: 0,
     browserWindowOptions:
      { width: 1300,
        height: 730,
        minWidth: 350,
        minHeight: 250,
        titleBarStyle: 'hidden',
        title: 'Inky' } },
  stopped: true,
  ended: false,
  evaluatingExpression: false,
  justRequestedDebugSource: false } WebContents {
  webContents: [Circular],
  history:
   [ 'file:///home/sam/GitHub/forks/inky/app/renderer/index.html' ],
  currentIndex: 0,
  pendingIndex: -1,
  inPageIndex: -1,
  _events:
   { 'navigation-entry-commited': [Function],
     'ipc-message': [Function],
     'ipc-message-sync': [Function],
     'ipc-internal-message': [Function],
     'ipc-internal-message-sync': [Function],
     'pepper-context-menu': [Function],
     'remote-require': [Function],
     'remote-get-global': [Function],
     'remote-get-builtin': [Function],
     'remote-get-current-window': [Function],
     'remote-get-current-web-contents': [Function],
     'remote-get-guest-web-contents': [Function],
     '-did-get-response-details': [Function],
     '-did-get-redirect-request': [Function],
     'devtools-reload-page': [Function],
     '-new-window': [Function],
     '-web-contents-created': [Function],
     '-add-new-contents': [Function],
     'will-navigate': [Function],
     'did-navigate': [Function],
     'devtools-opened': [Function],
     move: [Function],
     activate: [Function],
     'page-title-updated': [Function],
     'dom-ready': [ [Function], [Function] ] },
  _eventsCount: 25,
  _maxListeners: 0,
  browserWindowOptions:
   { width: 1300,
     height: 730,
     minWidth: 350,
     minHeight: 250,
     titleBarStyle: 'hidden',
     title: 'Inky' } }
```

**Comment by lunarcloud** [comment]
I tried to reproduce on Windows 10, and couldn't.
I'm only seeing this bug in Linux ( Kubuntu 19.10 to be specific )

**Comment by lunarcloud** [comment]
I discovered why my previous attempt at checking the requester failed. 
If I wrap *either* call to requester send in a check to see if destroyed, it works great. No try-catch needed.

**Comment by joethephish** [comment]
Perfect, thanks!

**Comment by ievgennaida** [comment]
The related issue was closed, but it was reproduced on windows, not on Linux. Hopefully, this fix will cover both systems...

**Pull request merged**
