### PR TITLE
Tag-based background images

### LINKED ISSUE #270: Tag-based image backgrounds
This is a feature proposal for a simple image background implementation for the inky default export template using tags. The `# IMAGE` tag already exists, which creates an image in the inky text stream.

This defines the additional image tag: `# IMAGEBG`

```
# IMAGEBG: images/castle.png
```

Usage: Define a `# IMAGEBG` tag on any line except a choice -- alone or after content. On export, the background is updated to the new image when ink loads the line. That's it.

Image files may be relative, or any valid urls. The link `//` must be escaped, `\/\/`.

```
# IMAGEBG: http:\/\/your.url.com/cafe.jpg
```

Clear the background with no argument.

```
# IMAGEBG: 
```

The implementation is a few lines in the default export template `main.js` and `main.css`:

```
  // IMAGEBG: src
  else if( splitTag && splitTag.property == "IMAGEBG" ) {
    outerScrollContainer.style.backgroundImage = 'url('+splitTag.val+')';
  }
```

```
    background-size: cover;
    background-repeat: no-repeat;
```

By default, background images are assumed to be full size (cover/no-repeat), not tiled textures. This can be changed by modifying the css.

This proposed solution is minimal, robustly non-opinionated about what constitutes a url, readable in plain text, and gives well-behaved and readable results in the Inky preview pane. It doesn't touch ink or Inky, just the template. The template behaves the same if no images are used, and images work well in both defined media modes.

This isn't an attempt to build in full visual novel support with characters -- there are separate project for that. But images that persist in the background rather than embedded in the stream do make it easier to block out scenes, model spatial navigation, and tie other development assets or concept art to the writing environment. For example:

```
- (stairs) The stairs   # IMAGEBG: stairs.jpg
  + study -> study
  + library -> library
- (study) The study     # IMAGEBG: study.jpg
  + stairs -> stairs
- (library) The library # IMAGEBG: library.jpg
  + stairs -> stairs 
```

This issue is for discussion, but I will submit a PR alongside the proposal.

### PR DESCRIPTION
**Pull request by jeremydouglass**
Simple tag-based background image control for the export template.
Supports both local files and escaped image urls: `http:\/\/foo.com/bar.png`
Defaults to full size.

Closes #270

### CODE REVIEW

**Comment by joethephish** [comment]
So in general I'm hesitant to overload the set of tags we support since I like the philosophy of having a very minimal main.js that is open to easy customisation by individual creators versus a fully featured system that the creator should never look at.

But actually, I kinda love both the background image and the audio tags you suggested. The code is lovely and simple / understandable.

However, what's the difference between IMAGEBG and IMAGEFG? I feel like maybe to keep things small we should just have one and call it "BACKGROUND"?

**Comment by jeremydouglass** [comment]
Very glad you like it!

Oops, I can drop that IMAGEFG commit--shouldn't have included it. IMAGEFG is the image-foreground (the text box or `.container`) and it is tiled by default -- so you load a texture behind your text to make it like papyrus or a circuit board or glass or whatever. 

BACKGROUND is nice too -- I can change IMAGEGB to that. The only downside I see is people might confuse it with CSS "background" and try to set it to a color.

**Comment by jeremydouglass** [comment]
Should be all cleaned up.

**Comment by joethephish** [comment]
Thanks!

**Pull request merged**
