### PR TITLE
Added restart, save-load, and theme-switch features to web export

### LINKED ISSUE #235: More features for Web Export
* Save / Load - author could decide not to
* Restart
* Switch Theme - because different readers prefer different things

### PR DESCRIPTION
**Pull request by lunarcloud**
Fix #235

### CODE REVIEW

**Comment by lunarcloud** [comment]
image

**Comment by lunarcloud** [comment]
Currently, save/load is on-by-default, and you can #no-save it off.
This could be flipped if preferred, off-by-default with a #savable global tag.

**Comment by joethephish** [comment]
These features are great, thank you! It's good to get them into the inky template since they're so commonly requested. I also like your design - it's a nice minimal addition that suits the template.

However, if you don't mind, would you mind trying to reduce and simplify the JavaScript as much as possible? One aim I have for the main.js is that it should be as short and simple as possible, so that for people who aren't experts with JavaScript, it's as easy as possible to customise and use as a jumping off point - even if this is the first time they've used JavaScript in their life! 

Concrete suggestions:

* I think we can assume that the majority of users have new enough browsers that we don't need to feature detect localStorage (assuming that's what's you're doing with `'localStorage' in window`), so let's not bother.
* Is `clickWork` really necessary? 
* Let's not bother with the "no-save" tag at all, we can just always show it if possible. The author can directly remove from the template if they like.
* Please try to include clear commenting above sections to explain what's going on! (See rest of file for style)
* Not sure why your localStorage keys are prefixed with "bit-"?
* Try to move as much of this stuff down to the bottom of the file as much as possible, to try to keep the ink related stuff as prominent as possible.

I wouldn't be nearly as precious about this stuff normally, I'm just really keen to keep this file super lightweight if possible. Thank you!

**Comment by lunarcloud** [comment]
1) fair enough
2) can and will remove
3) sure, will remove
4) I'll comb through and clean up
5) oops, this was leftover from a personal template, not intentional 
6) sure thing, makes sense

I'll go through and clean this all up when I get time. Thanks for reviewing it

**Comment by lunarcloud** [comment]
Hope that's better.

**Comment by Tayruh** [comment]
@lunarcloud 

I'm glad to see that someone manage to get these features into Ink. I guess I should have attempted to merge [this](https://github.com/inkle/ink/issues/547) into the project. I thought maybe the devs would see it, but I guess that didn't happen. Well, whichever. As long as the features get added.

One issue I had with my own version of the save/load stuff is that, depending on the situation, when you save a game, add/remove a line from your Ink file and then recompile it, and then load your game, the save file will break. All it would take was adding or removing one line to your ink file for it to break your save. It has something to do with how ink stores the current location in the story. Since I was only saving the state and current text output to localStorage, the breaking code was out of my reach. I have a feeling that your code probably has the same issue, although I haven't looked at it closely enough or grabbed a copy to test.

I think it'll be difficult for Ink to work as a platform in HTML with a bug like this, but it's probably outside of your scope as well. I think it's because Ink was designed more as a conversation model using labels as entry points instead of saving which line you last saw.

Anyway.. Good luck. I wasn't planning on working my save/load stuff anymore anyway, so it really is good to see this getting noticed.

**Comment by lunarcloud** [comment]
That's a wall 'o' text I'm not getting into. Scope of this change is smallish. Glad you like.

**Comment by jeremydouglass** [comment]
> when you save a game, add/remove a line from your Ink file and then recompile it, and then load your game, the save file will break

Is that issue reported? issue number? It would be nice if you have a recommended test.

> I have a feeling that your code probably has the same issue

Would you be able to test that?

**Comment by Tayruh** [comment]
It's incredibly easy to replicate in my system [here](https://github.com/inkle/ink/issues/547). (My computer is not set up to compile Ink and I don't really feel like doing it just to test this. Sorry.)

Using the demo game in the tutorial:
```
- I looked at Monsieur Fogg 
*	... and I could contain myself no longer.
	'What is the purpose of our journey, Monsieur?'
	'A wager,' he replied.
	* * 	'A wager!'[] I returned.
			He nodded. 
			* * * 	'But surely that is foolishness!'
			* * *  'A most serious matter then!'
			- - - 	He nodded again.
			* * *	'But can we win?'
					'That is what we will endeavour to find out,' he answered.
			* * *	'A modest wager, I trust?'
					'Twenty thousand pounds,' he replied, quite flatly.
			* * * 	I asked nothing further of him then[.], and after a final, polite cough, he offered nothing more to me. <>
	* * 	'Ah[.'],' I replied, uncertain what I thought.
	- - 	After that, <>
*	... but I said nothing[] and <> 
- we passed the day in silence.
- -> END
```
Compile the game. Click on a choice and save.

Then add a choice above the first choice in the game, so it looks like this:
```
* Test 
    Some test
*	... and I could contain myself no longer.
```
Compile and restart your game. Load your save. Watch the game crash.

The issue (based on my understanding of Ink, which may not be entirely correct) is that Ink seems to save every choice and label as an index, numbering them as they see them. The index of a previous choice or jump is also associated with a block of script, not to mention the entire callstack and all jump indexes are saved to the save state. How many times a label is seen is also assigned by index, not label name. So literally all it takes is adding a new item and it throws every single index off by one, making your save file completely out of sync with the current story file, and so it crashes.

I didn't report this issue because it's a deep flaw in Ink. If my understanding is correctly, it would involve completely re-engineering Ink to fix it. Ink is primarily designed for use as a dialogue system to be used inside a game like an RPG where you're not intended to save inside ongoing text. You're supposed only enter the Ink script through label calls. Or at least that's my understanding. Ink works fine that way. The way that the HTML save by accessing the story state while the story is currently running is not the intended way of using Ink.

But this is all based on my limited understanding of the Ink internals. Please correct me on anything I have misunderstood.

**Comment by lunarcloud** [comment]
Would you all put in an issue on the ink repo and not blow this simple pull request out of the water with this?

**Comment by Tayruh** [comment]
Sorry. I wasn't trying to spoil things. I just wanted to give you a heads up on something I came across during my time working on a similar thing.

I'm not going to post an issue suggesting they redesign their entire engine, which I think is required to fix this problem. If someone else would like to do that, feel free. The problem should be easy enough to replicate.

**Comment by joningold** [comment]
Ink is pretty robust to reloading changes in the ink, and had been for
several years. (a requirement for shipping games with it, as you say.) I’m
unsure of the issue you’re seeing here but perhaps you were using an older
version.

Either way we can discuss that on another issue if applicable.
-- 
Jazz, in Three-Four Time: A Novel
http://www.amazon.co.uk/dp/B004K1EYIE

**Comment by joethephish** [comment]
Thanks very much @lunarcloud, this is great!

**Pull request merged**
