### PR TITLE
Implement dark mode for About and Docs windows

### LINKED ISSUE #117: Dark Theme
Hello all,

I only started using Inky and so far I really find it very helpful, but something I always look for in any development environment is some form of dark theme to be a bit easier on the eyes after long hours.

### LINKED ISSUE #221: Any way to make the Editor dark?
The blinding white makes it difficult in the long run, would love a dark mode.

### PR DESCRIPTION
**Pull request by lunarcloud**
I think this will fix #221 and and complete fix #117

### CODE REVIEW

**Comment by joethephish** [comment]
Thanks! Hmm, the documentation window doesn't appear dark for me? (This is on macOS)

image

**Comment by lunarcloud** [comment]
Tested on Windows 10
image

**Comment by lunarcloud** [comment]
Tested on Kubuntu Linux 19.10
image

**Comment by lunarcloud** [comment]
I fired up Virtualbox and tested on MacOS Sierra:
image

**Comment by lunarcloud** [comment]
Fixed scrollbar colors, attached screenshots from each of the 3 OSes.

**Comment by joethephish** [comment]
Weird! I’ll try again later.

**Comment by lunarcloud** [comment]
Rebased, minimized the white flash of a new window opening

**Comment by joethephish** [comment]
Ah, my bad, I simply didn't do an `npm install` before `npm start`. Works for me now!

**Pull request merged**
