### PR TITLE
Knot/Stitch navigation added to sidebar

### PR DESCRIPTION
**Pull request by GreenCloversGames**
Added the much requested Knot/Stitch navigation tree to the sidebar. It's basic at the moment, it has every knot/stitch in the ink file, get's updated when a new knot/stitch is created. When you click on one, it takes you to the knot/stitch. It also highlights which knot/stitch the user is currently in.

### CODE REVIEW

**Comment by GreenCloversGames** [comment]
Solves issues #377 #23 #368

**Comment by joningold** [comment]
Hi! Could you paste in a screenshot of it in action?

**Comment by GreenCloversGames** [comment]
image
From the discord.

**Comment by GreenCloversGames** [comment]
Final commits made, ready for final check and to be merged!

**Comment by joethephish** [comment]
Awesome work, thanks for this!

**Pull request merged**
