### PR TITLE
Added Knot and Stitch Folding

### PR DESCRIPTION
**Pull request by greencloversguy**
Edited the ace-ink.js file to include inkFoldingRules. Now a fold toggle appears next to knot and stitch lines. Tested with the Intercept.

### CODE REVIEW

**Comment by Liance** [comment]
This is really cool! I've been playing around with this for a while, trying to look for edge cases, and it seems pretty robust.

There was one issue I came across though - knots are definable with three _or_ two equals signs (relevant part in the docs is [here](https://github.com/inkle/ink/blob/master/Documentation/WritingWithInk.md#writing-a-knot)).

It seems like the knots defined with two equals signs aren't recognized as being foldable (there's arguments for this being kept as a feature, I guess - maybe if someone doesn't want a knot to be counted as foldable - but I figured you should know about it).

image

Other than that, it's really cool - thank you for your work on this, I hope it makes its way into Inky proper!

**Comment by joethephish** [comment]
It’s actually 2+ equals signs in the compiler, the point is to allow you to allow you to style it how you like, eg:

    ====== big_knot ======

**Comment by greencloversguy** [comment]
Thanks for the feedback! I will try to fix this weekend, I think tinkering with the regular expressions should fix this.

**Comment by greencloversguy** [comment]
Just had a thought about this. Would it be worth having it so that Knots can be folded depending on the number of = signs they start with? For example, if I have a knot with 5 equal signs and I fold it, it will fold every knot with fewer equal signs into it as well. This might help writers organise their work.

**Comment by elliotherriman** [comment]
I've submitted a pull request to your branch, fixing that regex, as well as adding a shortcut to trigger that folding (control-L, to match alt-L, which folds any text you've selected). I can't promise it's great code, but it's working well on my end.

> Would it be worth having it so that Knots can be folded depending on the number of = signs they start with? For example, if I have a knot with 5 equal signs and I fold it, it will fold every knot with fewer equal signs into it as well.

I thought about this, but Inky doesn't recognise those as sub knots, is the trouble. Either something's a stitch, and it can be referred to using `knot.stitch` syntax, or it's a subsequent knot, meaning `-> knot1.knot2` will return an error. While I think that could be useful to help writers organise their documents, it would also imply that knots can be nested, which would really make things confusing to newcomers.

**Comment by joethephish** [comment]
> Just had a thought about this. Would it be worth having it so that Knots can be folded depending on the number of = signs they start with? For example, if I have a knot with 5 equal signs and I fold it, it will fold every knot with fewer equal signs into it as well. This might help writers organise their work.

Part of me loves this idea. But I think the reality is that it would be too confusing. If you fold a knot and some other knots appear to disappear for reasons you don't understand, that wouldn't be good news!

**Comment by joningold** [comment]
What might be more useful to consider (if not already implemented) is mid
level weave folding; it’s very easy  to accidentally break a weave with one
too few - marks ; being able to fold that up might help check it.
-- 
Jazz, in Three-Four Time: A Novel
http://www.amazon.co.uk/dp/B004K1EYIE

**Comment by greencloversguy** [comment]
> What might be more useful to consider (if not already implemented) is mid level weave folding; it’s very easy to accidentally break a weave with one too few - marks ; being able to fold that up might help check it. -- Jazz, in Three-Four Time: A Novel http://www.amazon.co.uk/dp/B004K1EYIE

Would like to work more on this, including having the folding work for choices as well, but I think that will be another pull request later down the line. I think the functionality here is useful enough to merge now. 



> I've submitted a pull request to your branch

I will look into this later on, makes me glad I took the time to prepare my code for future edits!

**Comment by greencloversguy** [comment]
Thanks to @elliotherriman, knots with 2 or more equal signs will now be folded as well. Going to continue development of choice folding in another branch, would like this to be merged in the meantime.

**Comment by joethephish** [comment]
Suuuuper cool, thanks!

**Pull request merged**
