### PR TITLE
Create Github Action to Build

### PR DESCRIPTION
**Pull request by lunarcloud**
Uses the build scripts on their respective OSes

### CODE REVIEW

**Comment by lunarcloud** [comment]
**Test running isn't included** because I can't get the tests to all pass even after setting it up to run headless via "xvfb-maybe electron-mocha".

**Comment by lunarcloud** [comment]
Running / output looks like this:
https://github.com/lunarcloud/inky/actions/runs/72253205

**Comment by lunarcloud** [comment]
To be fair, having only a bit of experience with GitHub actions (they're new), I don't know if pulling will work or if it's better to go to the tab, create a new workflow and copy my script.

**Comment by lunarcloud** [comment]
This is a run of the version of script I'm requesting: 
https://github.com/lunarcloud/inky/actions/runs/72916482

**Comment by joethephish** [comment]
This is cool! I've never played with GitHub actions so I have a couple of questions:

* Is this run on every push to master? Or just every official release? Or is it customisable?
* Does it / can it attach the binaries to the release post?

Overall I want to like it (I like shiny new toys!). However I want to make sure I fully understand what's going on, and I want to make sure that it wouldn't in fact make my life harder. Right now, running my local build script is not difficult, it simply takes a bit of time (include with upload etc). And if the build goes wrong, at least it goes wrong on my local machine for easier debugging.

**Comment by lunarcloud** [comment]
* When it runs is customizable, that's what line 2 is about.
  * It archives the binaries in a way that you wouldn't want to directly attach to the release, but extract the linux and mac archives first (the windows one looks ok). I don't know if it *does* though, as I've not tested making an actual release, though I can try.

You can see some amount of console log when expanding the steps in the job.
One benefit is that it'll build the Linux AppImage, which I don't think you'll be able to do from MacOS. Though, it's not hard to setup a virtual machine if you really wanted to do that yourself.

**Comment by lunarcloud** [comment]
More information about the triggers here:
https://help.github.com/en/actions/reference/events-that-trigger-workflows

**Comment by joethephish** [comment]
Sorry, I'm afraid I don't really see the benefits in using this. It's just as easy for me to set off a build locally if there's work to attach a latest build release anyway.

**Pull request closed without merging**
