### PR TITLE
initial testing

### PR DESCRIPTION
**Pull request by kennethlarsen**

### CODE REVIEW

**Comment by joethephish** [comment]
Hrm, given that the main `package.json` is in `app`, where would you suggest running `npm install --save-dev spectron`? Do you think it's worth adding a new `package.json` for running the tests?

**Comment by kennethlarsen** [comment]
I think it's safe to do in `app` and it shouldn't affect `package.json`. It could also be installed globally if that's preferred. In their documentation they just used `--saved-dev` instead of `-g.`

**Comment by joethephish** [comment]
If you use `--save-dev`, that's an instruction to add to the `package.json` under `devDependencies`. But yeah, that does no harm in the app's `package.json`.

**Comment by joethephish** [comment]
Hrm, still a bit confused though. With `/app` as my working directory (as described in `test.js`), I ran `mocha`, and got this error:

```
/usr/local/lib/node_modules/mocha/lib/utils.js:634
        throw new Error("cannot resolve path (or pattern) '" + path + "'");
        ^

Error: cannot resolve path (or pattern) 'test'
    at Object.lookupFiles (/usr/local/lib/node_modules/mocha/lib/utils.js:634:15)
    at /usr/local/lib/node_modules/mocha/bin/_mocha:327:30
    at Array.forEach (native)
    at Object.<anonymous> (/usr/local/lib/node_modules/mocha/bin/_mocha:326:6)
    at Module._compile (module.js:399:26)
    at Object.Module._extensions..js (module.js:406:10)
    at Module.load (module.js:345:32)
    at Function.Module._load (module.js:302:12)
    at Function.Module.runMain (module.js:431:10)
    at startup (node.js:141:18)
    at node.js:977:3
```

Where is the path to the `test.js` directory defined, or is that meant to be implicit in the way Spectron works somehow?

**Comment by kennethlarsen** [comment]
Oooh that's my bad. You have to go one directory up.

**Comment by joethephish** [comment]
Okay, I made some tweaks before merging:

- made it look up the path by platform automatically
- added the dev dependency to the `package.json`, so there's one less step for people to do to run the tests (since they should've run `npm install` already)
- Added a mac double-clickable `.command` file to run the tests.

**Pull request merged**
