### PR TITLE
Fixing weird fuzzaldrin-plus dependency bug

### LINKED ISSUE #112: Runtime exceptions (missing dependency?) on fresh build, OS X
Hey all, I'm trying to build inky on OS X (sierra, 10.12.6) from a fresh clone.
Node v6.11.2, npm v3.10.10

After cloning and running `./BUILD_FOR_MAC.command`, and launching inky...
I can open an ink file, but nothing runs in the right panel, and I can't quit or open another ink file in the left panel.

I get this exception in the inky console after I launch:
```
Uncaught Error: Cannot find module 'fuzzaldrin-plus'
    at Module._resolveFilename (module.js:470:15)
    at Function.Module._resolveFilename (/Volumes/Inky 1/Inky.app/Contents/Resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.Module._load (module.js:418:25)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Volumes/Inky 1/Inky.app/Contents/Resources/app.asar/renderer/goto.js:5:31)
    at Object.<anonymous> (/Volumes/Inky 1/Inky.app/Contents/Resources/app.asar/renderer/goto.js:426:3)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
```
Looks like it's trying to find the `fuzzaldrin` module but it can't?

Strange because I see fuzzaldrin-plus in app/node_modules/.
`RUN.command` gives the same runtime error.

### PR DESCRIPTION
**Pull request by awmcclain**
Fixes #112

### CODE REVIEW

**Comment by joethephish** [comment]
Actually, although it may not be working properly, this was intentional - I had to apply a hot fix to fuzzaldrin-plus for a feature that wasn't working properly. I followed a guide like this one to use a hot-fixed version of a package:

http://debuggable.com/posts/how-to-fork-patch-npm-modules:4e2eb9f3-e584-44be-b1a9-3db7cbdd56cb

Not sure why it's not working though?

**Comment by awmcclain** [comment]
I think that hotpatch has already been merged into their repo, so perhaps the URL isn't working correctly?

https://github.com/jeancroy/fuzz-aldrin-plus/commit/ad1b365fa44eb8f88643c85f1c486b08f9106576

**Comment by joethephish** [comment]
Oh, ok! I'm a bit of a noob with npm and versioning - do you know how can you see what an npm version corresponds to on github?

**Comment by awmcclain** [comment]
Ha! I'm not sure either, I think what's on npm is basically whatever is in the branch when they package it. I'm pretty sure that patch is the package for version 0.4.1, but I'll double check.

**Comment by joethephish** [comment]
Just saw your comment on the other repo - thanks for chasing it up!

**Comment by awmcclain** [comment]
Ok, I double checked and it _doesn't_ have the fix, so this PR will be a regression. I pinged the package owner to see if he or she will repackage. I'm not sure why the hotpatch URL isn't working.

**Comment by awmcclain** [comment]
I've updated a workaround until https://github.com/jeancroy/fuzz-aldrin-plus/ has a new package.
I forked fuzz-aldrin-plus and added the grunt script to the prepare directive so it runs when inky satisfies its dependencies.

The 'prepare' hook requires npm 4, though, so I added that to the fuzzaldrin requirements.

**Comment by awmcclain** [comment]
(Changes in my fork: https://github.com/jeancroy/fuzz-aldrin-plus/compare/master...awmcclain:master)

**Comment by joethephish** [comment]
Okay, merged in! When testing it out it required me updating npm (and as a consequence, node too), but all now seems to work great.

Thanks so much for working through this particularly thorny issue!

**Comment by awmcclain** [comment]
You're welcome! It's a pain.

For future reference (as I learned while fiddling with this), you can upgrade npm separately from node if you `npm install -g npm@5.4`. (which also pegs npm at 5.4 since there's a SEPARATE issue where npm 5.3 breaks `electron-packager`)

**Pull request merged**
