### PR TITLE
Add Custom Completer

### LINKED ISSUE #29: Gathers auto-completing when they shouldn't be
When you have a few bits of nesting in your code, inky starts to autocomplete your gathers to whichever one you've been using the most. It also recognises TAB as accepting the auto-complete so indenting after a gather point will automatically create a nested gather when you don't want it to.

### PR DESCRIPTION
**Pull request by arashikou**
This pull request resolves #29 and #21 by implementing a custom completer for Inky. This replaces the `textCompleter` included by default in ACE, which was causing headaches for some people by suggesting every word from the text (including _punctuation_) as an auto-complete suggestion.

`inkCompleter` pulls flow-control symbol names from `InkFileSymbols`. `InkFileSymbols` has also been upgraded to parse out variable names, which are likewise used by the completer to provide suggestions. `inkCompleter` will pull suggestions from all files in the current project, not just the current file.

In addition to suggestions generated by `inkCompleter` based on the user's source files, `ace-ink-mode` now provides Ink keywords as suggested completions, which are then supplied to the auto-completer by ACE's built-in `keyWordCompleter`.

Explicitly not covered by this pull request:

- Tags. I'm not sure how they're used, since they're not covered by [Writing With Ink](https://github.com/inkle/ink/blob/master/Documentation/WritingWithInk.md), so I didn't feel comfortable making the call as to whether they should be included in the suggestions. Since `InkFileSymbols` already parses them, adding them to `inkCompleter` later &mdash; if desired &mdash; should be simple enough.
- Determining which files in the current project are actually included by the current source file. Right now, `inkCompleter` provides suggestions based on all files that are currently in the project.

## TODO List
Based on the discussion that follows.

- [x] Pull in prose suggestions
- [x] Make completer context-aware to only suggest appropriate completions for the current cursor location
- [x] Add LISTs to `InkFileSymbols` as variable names
- [x] Add LIST name parsing to `ace-ink`
- [x] Suggest known knot names when writing a new knot, to support the "write divert first, knot second" workflow.
- [x] Make suggestion-generation asynchronous.

### CODE REVIEW

**Comment by joethephish** [comment]
So, I'm afraid I can't immediately accept this, despite the fact that you've clearly done some great work!

Internally we actually make use of the body text word completion - it's useful especially for character and location names that are a little tricky to spell! However, I *totally* get where you're coming from with the overzealous default completer (esp with punctuation).

So, to fix that, I'd suggest adding an extra feature to the completer that accepts all words too (maybe `\b\w{3,}\b`?), but on a menu option for people who prefer not?

Is it even possible to have the completer determine which suggestions to provide based on the known context? So if you're in main text it provides text suggestions... it could even detect that you're in a divert if you've just written a `->` and provide knot suggestions, and suggest both variables and knots if you're in logic. More advanced feature certainly, but would be cool if it's possible!

To answer your questions:

* Tags are now mentioned in the writing tutorial [here](https://github.com/inkle/ink/blob/master/Documentation/WritingWithInk.md#tags) and in a more complete way in the "running your ink" doc [here](https://github.com/inkle/ink/blob/master/Documentation/RunningYourInk.md#marking-up-your-ink-content-with-tags). The question of whether or not they should be in the completer
* Determining which files are included: Despite the possibility of using hierarchical includes, the namespaces aren't limited to just the current ink file and its own includes. Rather, everything should be visible across all files - so what you have is correct.

Looping in @joningold since as our lead writer, any decisions should get the final okay from him either way!

**Comment by joningold** [comment]
This is a really interesting commit that's giving me a lot of to think
about, to be honest. The completer is *definitely* most useful for variable
/ knot names, and being cross-file is brilliant.

While I do use the completer as Joe said, for normalising spellings, if
it's cross file then this list is going to get really, really big. So I
think I might give this PR a try and see "how it plays". It's a big enough
change that I wouldn't want to roll it into inky without really trying out
how it affects the writing process (or at least without the option of
putting it on a user presence) - but that said it does sound pretty handy.

If I understood the second "not done" point correctly, I think the
completer should reference all files and not just files "below" the current
file - ink files are, in general, global and not hierarchical.

Jon

**Comment by Julisep** [comment]
I just want to add that this change is awesome (and runs in my small test very well).

Great Job

**Comment by arashikou** [comment]
You all are too kind! Thank you for taking a look at my pull request. Do not worry about asking me to revise the change before you can accept it. Coming from more of a code-writing background than a prose-writing background, the value of auto-completing text words (just not punctuation) hadn't occurred to me.

---

> Is it even possible to have the completer determine which suggestions to provide based on the known context?

This is definitely possible. ACE gives the completer info about the cursor's location in the document (which my code currently ignores) specifically for this sort of purpose where you want to offer different completion suggestions based on context.

> Tags are now mentioned in the writing tutorial here and in a more complete way in the "running your ink" doc here. The question of whether or not they should be in the completer - not sure to be honest. My instinct is that tag text is quite similar to body text.

Thanks for the links. I understand tags better now. For now, I think we should treat tags as body text, rather than separately, and see how that feels.

> I think the completer should reference all files and not just files "below" the current file - ink files are, in general, global and not hierarchical.

OK, great. Then it sounds like the current behavior (including suggestions from all files in the project) is the most desirable behavior anyway.

> While I do use the completer as Joe said, for normalising spellings, if it's cross file then this list is going to get really, really big.

That's a good point. One possibility here is to only suggest text completions for the current file while still pulling variable & target completions from all files. I'm not sure if that would be confusingly inconsistent or life-saving in large projects.

> I just want to add that this change is awesome

Thank you! I'm glad you're enjoying it.

---

Given everything you all have said, I think the best option is to make the completer include body text again, but to also make the completer context-aware so that:

- If the last thing typed was a divert, suggest divert targets.
- If the current typing area is in the middle of logic, suggest divert targets and variables.
- Otherwise, suggest body text words at least three characters in length. This includes text from tags.

The only open question I have is which of these should be drawn from all files and which should only be drawn from the current file.

If that sounds good to you after you've had some time to play with this PR, I would be happy to work on making it happen. I look forward to hearing the results of your playing with this PR.

**Comment by joningold** [comment]
Hey! I've had a chance to play with this now, and - yeah, it's fantastic. A few points of feedback, most of which agree with what's been said above:-

- it'd be great if the complete was context-aware, so if I'm typing content it doesn't suggest knots / variables. Having it suggest vocab words here would be great; sourced from across the project would seem sensible to me. 

- I found that variables defined via LISTS weren't included in the completion, which is probably just because the LIST type is new. 

Otherwise, this is amazing functionality / semi-magical. 

cheers!
jon

**Comment by arashikou** [comment]
Glad you're liking it so much!

> it'd be great if the complete was context-aware, so if I'm typing content it doesn't suggest knots / variables. Having it suggest vocab words here would be great; sourced from across the project would seem sensible to me.

OK, I will see about implementing this as we discussed above.

> I found that variables defined via LISTS weren't included in the completion, which is probably just because the LIST type is new.

It's pulling the list of variable names from `InkFileSymbols`. It doesn't look like that has been updated to account for lists yet. I'll see about adding that, unless that's something you're already doing internally.

I've added a TODO list to the top of the Pull Request.

**Comment by joethephish** [comment]
> It's pulling the list of variable names from InkFileSymbols. It doesn't look like that has been updated to account for lists yet. I'll see about adding that, unless that's something you're already doing internally.

Yeah, it's not doing ink list items right now. Something to bear in mind if you add support for it: in the ace mode, it parses list items using a simple regex: `/([\w\(\)=\d\s]+)/`, and this is designed to support the entirety of for example `myListItem`, `myListItem = 9`, `(myListItem) = 9`, `(myListItem = 9)`, since the syntax is quite flexible. So before storing it as a symbol, you'd have to strip out the rest of that stuff.

The identifier is just `\b\w+\b`, except that it should reject anything that is purely `\d+` (this differs slightly from C-like languages that usually reject anything that *starts* with `\d`).

**Comment by arashikou** [comment]
I apologize for the long silence on this. I have not has as much free time lately. I expect to find time to resolve this soon, however.

**Comment by arashikou** [comment]
Thanks for the tip on how to properly handle the output of `ace-ink` when it parses list items, @joethephish. That was a huge help in figuring out how to add LIST support. I had to add additional matches to `ace-ink` to match the name of the LIST itself, since that wasn't being matched anywhere before. I hope that is OK.

These latest patches add Vocab and LIST support, but I am still working on contextual completion-suggestion. Right now, you will get flooded with a mixture of Keyword, Variable, and Vocab suggestions if you use this PR.

**Comment by arashikou** [comment]
The completer should now limit what it suggests based on context. This ended up being much simpler than I initially thought. When I was doing my first implementation, I didn't realize I could use the tokenizer to figure out the context for me, so I was having to duplicate or borrow a lot of the parsing. The version you see here is _much_ cleaner than that.

With that commit, I believe everything we discussed before is taken care of. Let me know if you have any further feedback after trying this latest version out!

**Comment by joningold** [comment]
Hey!

I've given it a go on our current project here, and found a couple of issues, one fairly minor (but may be hard to solve); and the other a bit bigger (but hopefully easy to fix!) 

1) The minor issue is that if I write:

-> new_knot 

and then begin to create "new_knot", it doesn't offer "new_knot" as a suggestion.

2) The more major issue is the speed; each keypress is taking about 0.1 sec - because our project is really, really big, with about fifty include files. It looks like the code is parsing through all of that on every keypress to build the vocab lists. 

From what I can tell, it should be possible to build the vocab lists asynchronously and use the cached results to populate the popup?

Otherwise, it's pretty cool..!!

**Comment by arashikou** [comment]
Thank you for giving this a try. It's useful to hear how it handles larger projects, and I imagine there are none larger than yours! I will look into that first problem, as well as making the suggestion-building asynchronous. More generally, I will look into any ways to make this more efficient.

**Comment by arashikou** [comment]
The completer should now suggest knot names that were only used in a divert before but don't actually exist yet and will now suggest known knot names when writing new knots. (or other named flow points)

Making the parsing asynchronous was really straightforward. InkFileSymbols already handles asynchronously parsing the file after a batch of changes, so the fix was just to not provoke a re-parse when preparing suggestions in the completer. Can you please try this on your large projects and see if the performance is improved?

(BTW, as a point of order, if you'd like me to squash these changes before you merge them, for the sake of Git history cleanliness, just say the word. I've been keeping them all separate in case the context of change over time is useful in understanding the code.)

**Comment by joethephish** [comment]
Thanks for making these changes. Jon and I are on holiday right now, but we'll give them a try as soon as we get back :) Excited to give the latest version a go!

And in terms of squashing commits - we prefer to keep them intact - we like to see the context over time too.

**Comment by arashikou** [comment]
Excellent! Have a lovely holiday.

**Comment by joningold** [comment]
Hey! First impressions -- this is very, very fast, significantly faster to
use than the main inky build. Which is really great!

I'll use it a bit more to see if I can find any cases where it completes
the wrong way / does anything else unhelpful - the problem with it being
context-aware is it needs to get the context *right*. But my initial run is
extremely promising, and I'll use this is as my "working" build from here.
Thank you !!

cheers
jon

**Comment by joethephish** [comment]
Thanks so much for working with us on this - we've been writing with it and it's great, so I've now merged it in :) We'll put out a new release of inky soon.

**Comment by arashikou** [comment]
Awesome! Thank you so much for working with _me_.

**Pull request merged**
