### PR TITLE
Added zoom % menu

### PR DESCRIPTION
**Pull request by tk2487**
Thought it would be convenient to have a font size menu in addition to the zoom menu. This will let users switch to a specific font size they want (within the given range) instead of zooming in and out a random number of times. *Zoom function is left untouched*

Screen Shot 2020-05-13 at 11 14 28 PM

### CODE REVIEW

**Comment by joethephish** [comment]
Cool, thanks for the PR!

Hmmm. First instinct - that’s a lot of numbers! I feel like half that number would be okay? Second instinct - I was quite surprised it’s in font sizes as opposed to % zoom levels. I quite like the latter because you know what 100% is, whereas with font sizes for most people it’s probably quite arbitrary?

**Comment by jeremydouglass** [comment]
Hmm. TextMate, TextEdit, Atom all have "Increase Font / Decrease Font" or "Bigger / Smaller" --  rather than a number list.

TextEdit has both zoom and font size for RTF page mode -- they do different things -- but for the plain text programming editors I think font +/- is instead of zoom, rather than in addition to zoom.

**Comment by tk2487** [comment]
Okay I changed the menu to Zoom % so it makes more sense.

Screen Shot 2020-05-14 at 7 14 47 AM

**Comment by joethephish** [comment]
Lovely, thanks!

**Pull request merged**
