### PR TITLE
Implementation of a Doucumentation

### PR DESCRIPTION
**Pull request by Julisep**

### CODE REVIEW

**Comment by joethephish** [comment]
Awesome, thanks for your work on this! Before I accept the PR, I'd need a few changes:

* Currently it won't work in a release build, only in development. You put the actual Documentation directory within resources, which is inaccessible from a release build. Only files that are in `app` will be bundled. You can test a release build either with `BUILD_PACKAGE.command` (on mac) or `BUILD_FOR_WINDOWS.bat` (on windows).
    * I'm just realising that you may still have issues though since we package files into an [asar](https://github.com/electron/electron/blob/master/docs/tutorial/application-packaging.md). You might want to follow the documentation on how to get files out of it, or find a way to exclude them from the asar. See `--asar-unpack-dir` in the release build scripts. This can be a bit tricky I'm afraid :-( We might need to create a "resources" directory within "app", and include "ink" and "documentation" within there, and make the resources directory the unpack directory, since as far as I can tell, it doesn't seem possible to have more than one?
* I noticed your comment "Till we have a real documentation (not the WritingWitInk.md tutorial) this button can be ignored". Actually, I reckon we can turn the tutorial into "real documentation" simply by adding some section titles in your sidebar, and jump to `#` anchors on the page. We can possibly rename them (within the sidebar only) for clarity if necessary. The HTML page you included correctly generated `id` attributes for the sections.

Not necessary, but would be nice:

* What did you use to generate the HTML from the markdown? Or did you simply download the HTML from github? It might be good to generate the HTML from the markdown as a build step. Not sure whether this can be automatically done when running `npm start` or `npm install` or something... (or indeed simply at runtime?)

**Comment by joethephish** [comment]
Also, I noticed that `tutorial.html` has an online CSS link: `<link rel="stylesheet" href="http://www.w3schools.com/lib/w3.css">`. Given that this is an offline app, we should bundle all of our resources.

To be honest, I'm not entirely sure why it's necessary to include it at all? Given that we bundle a fixed implementation browser with the app, there's no reason to do any kind of CSS normalisation. I'd say we should just use vanilla HTML and CSS. Is it because the HTML comes from github...?

**Comment by Julisep** [comment]
The documentation is now generated on start from the markdownfile.
I also implemented all your requests.

**Comment by joethephish** [comment]
Hrm, just tried to run `npm install` and `npm start` and I got this error:

```
> inky@0.3.1 start /Users/phish/inkle/projects/inky/app
> node renderer/createDocumentnavigation.js && markdown-html resources/Documentation/WritingWithInk.md -s resources/Documentation/documentation.css -o renderer/embeddedDocumentation.html &&  electron main-process/main.js

/Users/phish/inkle/projects/inky/app/renderer/createDocumentnavigation.js:28
                let activeMark = mark.split('x');
                ^^^

SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode
    at exports.runInThisContext (vm.js:54:16)
    at Module._compile (module.js:375:25)
    at Object.Module._extensions..js (module.js:406:10)
    at Module.load (module.js:345:32)
    at Function.Module._load (module.js:302:12)
    at Function.Module.runMain (module.js:431:10)
    at startup (node.js:141:18)
    at node.js:977:3

npm ERR! Darwin 15.5.0
npm ERR! argv "/usr/local/Cellar/node/5.2.0/bin/node" "/usr/local/bin/npm" "start"
npm ERR! node v5.2.0
npm ERR! npm  v3.3.12
```

**Comment by joethephish** [comment]
Cool, that worked, and doc viewer is coming together really nicely!

I'm afraid the packaged app version isn't working right now. I'm getting this error:

image

Are you happy with building app packages for testing?

It looks like you're still referencing stuff outside of the `/app` directory too. I noticed [this line](https://github.com/Julisep/inky/blob/6aed56d51c3871db0b8654ba9e01272cc7e82cd4/app/renderer/documentationWindow.html#L6) for example.

A few more minor issues:

* I'm missing the font `Segoe UI` - is it maybe a Windows one?
* This line doesn't close the `<li>` properly (missing slash). Same with two lines below.
* In the `.gitignore` you added a [couple of lines](https://github.com/Julisep/inky/blob/6aed56d51c3871db0b8654ba9e01272cc7e82cd4/.gitignore#L8) for files that are automatically generated, which is good... except that they seem to be in the repo anyway? What's the reason for using dots rather than slashes in the paths btw?
* I believe that the `markdown-html` package is only used during development, it doesn't need to be embedded in the app itself? So, it should be possible to add the package to `devDependencies` instead? i.e. right  below [spectron](https://github.com/Julisep/inky/blob/6aed56d51c3871db0b8654ba9e01272cc7e82cd4/app/package.json#L27). Oh, it looks like at one stage you did do that... any reason you changed it?
* Minor project organisation: Maybe put the documentation related files in a subfolder within `renderer`? Also, `createDocumentnavigation.js` is effectively a build script... could that be pulled outside of `/app` entirely...?
* Could you explain how the [marks](https://github.com/Julisep/inky/blob/6aed56d51c3871db0b8654ba9e01272cc7e82cd4/app/renderer/createDocumentnavigation.js#L2) thing works, and what's going on [on this line](https://github.com/Julisep/inky/blob/6aed56d51c3871db0b8654ba9e01272cc7e82cd4/app/renderer/createDocumentnavigation.js#L20)? (Maybe add some code comments!)
* When generating the different styled titles for the nav, I'd suggest you don't use `<b>` tags (which are really old fashioned HTML!) and instead maybe generate something like: `<li><a class="nav-h1" ...`, for all of the `h1` to `h6` that are used. Then we can style them in the CSS.

I'll play with the CSS and help with a styling pass when I merge in.

**Comment by Julisep** [comment]
I fixed the following thing:

- I replaced Segoe UI (which is inded a Windows one) with the ones used in the project window: Helvetica, sans-serif 
- markdown-html is again in devDependencies (I changed this back then because of a small problem with git)
- commentary was added
- the project organisation is improved
- I changed the style as suggested

**Comment by joethephish** [comment]
Currently getting this error:

```
> inky@0.3.1 start /Users/phish/inkle/projects/inky/app
> node ../build/createDocumentnavigation.js && markdown-html resources/Documentation/WritingWithInk.md -s resources/Documentation/documentation.css -o renderer/documentation/embedded.html &&  electron main-process/main.js

{ [Error: ENOENT: no such file or directory, open '../app/renderer/documentation/window.html']
  errno: -2,
  code: 'ENOENT',
  syscall: 'open',
  path: '../app/renderer/documentation/window.html' }
stream.js:75
      throw er; // Unhandled stream error in pipe.
      ^

Error: ENOENT: no such file or directory, open '/Users/phish/inkle/projects/inky/app/renderer/documentation/embedded.html'
    at Error (native)
```

**Comment by joethephish** [comment]
It looks like it's simply that the output directory for the built documentation doesn't exist by default. I fixed by adding the lines:

`const mkdirp = require('mkdirp');`

at the top of `createDocumentationnavigation.js` and:

`mkdirp.sync("../app/renderer/documentation/");`

right before   `fs.writeFile('../app/renderer/documentation/window.html'`

**Comment by joethephish** [comment]
However, I'm afraid release builds still aren't running (same screenshot I posted above).

**Comment by joethephish** [comment]
Oh, weirdly, it seemed to just be a case sensitivity issue! I changed the line:

`const DocumentationWindow = require("./documentationWindow.js").DocumentationWindow;`

to be:

`const DocumentationWindow = require("./DocumentationWindow.js").DocumentationWindow;`

and the release build works!

**Comment by joethephish** [comment]
Thanks for all your hard work on this, it's now merged!

**Pull request merged**
